################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
DDCRx.obj: D:/WorkLocation/Code_736/Code_736/src/steMgr/dataIf/src/DDCRx.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/bin/cl6x" -mv6600 --abi=eabi -O2 -g --include_path="D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/dataIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/3rdParty/gsmL1/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/genutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/gsmutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steDrv/platform/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/CommandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/diagif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/status/include" --include_path="D:/TInew/ipc_3_21_00_07/packages" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/dataIf" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/platform/evmc6678l/platform_lib/include" --include_path="D:/TInew/uia_1_03_01_08/packages" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages" --include_path="D:/TInew/xdctools_3_25_03_72/packages" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="D:/TInew/bios_6_37_02_27/packages" --gcc --define=_DEBUG --define=_TMS320C6400 --display_error_number --diag_warning=225 --opt_for_speed=3 --preproc_with_compile --preproc_dependency="DDCRx.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

DDC_CopySamples.obj: D:/WorkLocation/Code_736/Code_736/src/steMgr/dataIf/src/DDC_CopySamples.asm $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/bin/cl6x" -mv6600 --abi=eabi -O2 -g --include_path="D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/dataIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/3rdParty/gsmL1/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/genutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/gsmutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steDrv/platform/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/CommandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/diagif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/status/include" --include_path="D:/TInew/ipc_3_21_00_07/packages" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/dataIf" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/platform/evmc6678l/platform_lib/include" --include_path="D:/TInew/uia_1_03_01_08/packages" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages" --include_path="D:/TInew/xdctools_3_25_03_72/packages" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="D:/TInew/bios_6_37_02_27/packages" --gcc --define=_DEBUG --define=_TMS320C6400 --display_error_number --diag_warning=225 --opt_for_speed=3 --preproc_with_compile --preproc_dependency="DDC_CopySamples.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

DataRouter.obj: D:/WorkLocation/Code_736/Code_736/src/steMgr/dataIf/src/DataRouter.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/bin/cl6x" -mv6600 --abi=eabi -O2 -g --include_path="D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/dataIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/3rdParty/gsmL1/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/genutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/gsmutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steDrv/platform/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/CommandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/diagif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/status/include" --include_path="D:/TInew/ipc_3_21_00_07/packages" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/dataIf" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/platform/evmc6678l/platform_lib/include" --include_path="D:/TInew/uia_1_03_01_08/packages" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages" --include_path="D:/TInew/xdctools_3_25_03_72/packages" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="D:/TInew/bios_6_37_02_27/packages" --gcc --define=_DEBUG --define=_TMS320C6400 --display_error_number --diag_warning=225 --opt_for_speed=3 --preproc_with_compile --preproc_dependency="DataRouter.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

DspToIpu.obj: D:/WorkLocation/Code_736/Code_736/src/steMgr/dataIf/src/DspToIpu.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/bin/cl6x" -mv6600 --abi=eabi -O2 -g --include_path="D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/dataIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/3rdParty/gsmL1/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/genutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/gsmutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steDrv/platform/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/CommandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/diagif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/status/include" --include_path="D:/TInew/ipc_3_21_00_07/packages" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/dataIf" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/platform/evmc6678l/platform_lib/include" --include_path="D:/TInew/uia_1_03_01_08/packages" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages" --include_path="D:/TInew/xdctools_3_25_03_72/packages" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="D:/TInew/bios_6_37_02_27/packages" --gcc --define=_DEBUG --define=_TMS320C6400 --display_error_number --diag_warning=225 --opt_for_speed=3 --preproc_with_compile --preproc_dependency="DspToIpu.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

QueDeque.obj: D:/WorkLocation/Code_736/Code_736/src/steMgr/dataIf/src/QueDeque.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/bin/cl6x" -mv6600 --abi=eabi -O2 -g --include_path="D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/dataIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/3rdParty/gsmL1/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/genutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/gsmutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steDrv/platform/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/CommandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/diagif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/status/include" --include_path="D:/TInew/ipc_3_21_00_07/packages" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/dataIf" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/platform/evmc6678l/platform_lib/include" --include_path="D:/TInew/uia_1_03_01_08/packages" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages" --include_path="D:/TInew/xdctools_3_25_03_72/packages" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="D:/TInew/bios_6_37_02_27/packages" --gcc --define=_DEBUG --define=_TMS320C6400 --display_error_number --diag_warning=225 --opt_for_speed=3 --preproc_with_compile --preproc_dependency="QueDeque.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


