################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
CriticalMem.obj: D:/WorkLocation/Code_736/Code_736/src/steApp/src/CriticalMem.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/bin/cl6x" -mv6600 --abi=eabi -O2 -ms0 -g --include_path="D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/gsmutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steApp/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/genutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/3rdparty/gsmL1/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/dataif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/Commandif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stemgr/status/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stedrv/platform/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/diagIf/include" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/platform/evmc6678l/platform_lib/include" --gcc --define=_CORE5 --define=_TMS320C6400 --display_error_number --diag_warning=225 --opt_for_speed=3 --gen_opt_info=0 --call_assumptions=0 --preproc_with_compile --preproc_dependency="CriticalMem.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

EthBuff.obj: D:/WorkLocation/Code_736/Code_736/src/steApp/src/EthBuff.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/bin/cl6x" -mv6600 --abi=eabi -O2 -ms0 -g --include_path="D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/gsmutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steApp/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/genutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/3rdparty/gsmL1/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/dataif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/Commandif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stemgr/status/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stedrv/platform/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/diagIf/include" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/platform/evmc6678l/platform_lib/include" --gcc --define=_CORE5 --define=_TMS320C6400 --display_error_number --diag_warning=225 --opt_for_speed=3 --gen_opt_info=0 --call_assumptions=0 --preproc_with_compile --preproc_dependency="EthBuff.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

HeapMem.obj: D:/WorkLocation/Code_736/Code_736/src/steApp/src/HeapMem.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/bin/cl6x" -mv6600 --abi=eabi -O2 -ms0 -g --include_path="D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/gsmutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steApp/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/genutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/3rdparty/gsmL1/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/dataif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/Commandif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stemgr/status/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stedrv/platform/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/diagIf/include" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/platform/evmc6678l/platform_lib/include" --gcc --define=_CORE5 --define=_TMS320C6400 --display_error_number --diag_warning=225 --opt_for_speed=3 --gen_opt_info=0 --call_assumptions=0 --preproc_with_compile --preproc_dependency="HeapMem.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

MemMgr.obj: D:/WorkLocation/Code_736/Code_736/src/steApp/src/MemMgr.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/bin/cl6x" -mv6600 --abi=eabi -O2 -ms0 -g --include_path="D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/gsmutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steApp/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/genutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/3rdparty/gsmL1/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/dataif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/Commandif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stemgr/status/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stedrv/platform/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/diagIf/include" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/platform/evmc6678l/platform_lib/include" --gcc --define=_CORE5 --define=_TMS320C6400 --display_error_number --diag_warning=225 --opt_for_speed=3 --gen_opt_info=0 --call_assumptions=0 --preproc_with_compile --preproc_dependency="MemMgr.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

ModMgr.obj: D:/WorkLocation/Code_736/Code_736/src/steApp/src/ModMgr.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/bin/cl6x" -mv6600 --abi=eabi -O2 -ms0 -g --include_path="D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/gsmutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steApp/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/genutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/3rdparty/gsmL1/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/dataif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/Commandif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stemgr/status/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stedrv/platform/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/diagIf/include" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/platform/evmc6678l/platform_lib/include" --gcc --define=_CORE5 --define=_TMS320C6400 --display_error_number --diag_warning=225 --opt_for_speed=3 --gen_opt_info=0 --call_assumptions=0 --preproc_with_compile --preproc_dependency="ModMgr.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

RxCalib.obj: D:/WorkLocation/Code_736/Code_736/src/steMgr/status/src/RxCalib.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/bin/cl6x" -mv6600 --abi=eabi -O2 -ms0 -g --include_path="D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/gsmutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steApp/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/genutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/3rdparty/gsmL1/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/dataif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/Commandif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stemgr/status/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stedrv/platform/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/diagIf/include" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/platform/evmc6678l/platform_lib/include" --gcc --define=_CORE5 --define=_TMS320C6400 --display_error_number --diag_warning=225 --opt_for_speed=3 --gen_opt_info=0 --call_assumptions=0 --preproc_with_compile --preproc_dependency="RxCalib.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

configPkg/linker.cmd: ../TRS_SYSBIOS.cfg
	@echo 'Building file: $<'
	@echo 'Invoking: XDCtools'
	"D:/TInew/xdctools_3_25_03_72/xs" --xdcpath="D:/TInew/bios_6_37_02_27/packages;D:/TInew/pdk_C6678_1_1_2_6/packages;D:/TInew/uia_1_03_01_08/packages;D:/TInew/ccsv5/ccs_base;D:/WorkLocation/TRS_MEM_PARTITION;D:/TInew/ipc_3_21_00_07/packages;D:/TInew/xdctools_3_25_03_72;" xdc.tools.configuro -o configPkg -t ti.targets.elf.C66 -p myBoard_Core5_m -r debug -c "D:/TInew/ccsv5/tools/compiler/c6000_7.4.4" --compileOptions "-g --optimize_with_debug" "$<"
	@echo 'Finished building: $<'
	@echo ' '

configPkg/compiler.opt: | configPkg/linker.cmd
configPkg/: | configPkg/linker.cmd

main.obj: D:/WorkLocation/Code_736/Code_736/src/steApp/src/main.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/bin/cl6x" -mv6600 --abi=eabi -O2 -ms0 -g --include_path="D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/gsmutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steApp/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/genutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/3rdparty/gsmL1/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/dataif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/Commandif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stemgr/status/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stedrv/platform/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/diagIf/include" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/platform/evmc6678l/platform_lib/include" --gcc --define=_CORE5 --define=_TMS320C6400 --display_error_number --diag_warning=225 --opt_for_speed=3 --gen_opt_info=0 --call_assumptions=0 --preproc_with_compile --preproc_dependency="main.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

statmgr.obj: D:/WorkLocation/Code_736/Code_736/src/steMgr/status/src/statmgr.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/bin/cl6x" -mv6600 --abi=eabi -O2 -ms0 -g --include_path="D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/gsmutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steApp/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/genutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/3rdparty/gsmL1/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/dataif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/Commandif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stemgr/status/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stedrv/platform/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/diagIf/include" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/platform/evmc6678l/platform_lib/include" --gcc --define=_CORE5 --define=_TMS320C6400 --display_error_number --diag_warning=225 --opt_for_speed=3 --gen_opt_info=0 --call_assumptions=0 --preproc_with_compile --preproc_dependency="statmgr.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


