################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
RxCalib.obj: D:/WorkLocation/Code_736/Code_736/src/steMgr/status/src/RxCalib.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"D:/TInew/ccsv5/tools/compiler/c6000_7.3.4/bin/cl6x" -mv6600 -g --gcc --define=_DEBUG --include_path="D:/TInew/ipc_3_21_00_07/packages" --include_path="D:/TInew/ccsv5/tools/compiler/c6000_7.3.4/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steDrv/platform/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/include" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/platform/evmc6678l/platform_lib/include" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="../" --include_path="/packages/ti/xdais" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/status/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stemgr/diagif/include" --include_path="../" --include_path="../" --include_path="../" --include_path="../" --include_path="/ti/csl" --include_path="/ti/platform/evmc6678l/platform_lib/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/commandif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stedrv/platform/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stelib/genutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stelib/commandif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/3rdparty/gsml1/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stelib/gsmutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/dataif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/diagif/include" --include_path="../" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/status/include" --include_path="D:/TInew/xdctools_3_25_03_72/packages" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/genutil/include" --include_path="D:/TInew/bios_6_37_02_27/packages" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/commandIf/include" --display_error_number --diag_warning=225 --abi=eabi --preproc_with_compile --preproc_dependency="RxCalib.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

statmgr.obj: D:/WorkLocation/Code_736/Code_736/src/steMgr/status/src/statmgr.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"D:/TInew/ccsv5/tools/compiler/c6000_7.3.4/bin/cl6x" -mv6600 -g --gcc --define=_DEBUG --include_path="D:/TInew/ipc_3_21_00_07/packages" --include_path="D:/TInew/ccsv5/tools/compiler/c6000_7.3.4/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steDrv/platform/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/include" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/platform/evmc6678l/platform_lib/include" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="../" --include_path="/packages/ti/xdais" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/status/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stemgr/diagif/include" --include_path="../" --include_path="../" --include_path="../" --include_path="../" --include_path="/ti/csl" --include_path="/ti/platform/evmc6678l/platform_lib/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/commandif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stedrv/platform/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stelib/genutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stelib/commandif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/3rdparty/gsml1/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stelib/gsmutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/dataif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/diagif/include" --include_path="../" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/status/include" --include_path="D:/TInew/xdctools_3_25_03_72/packages" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/genutil/include" --include_path="D:/TInew/bios_6_37_02_27/packages" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/commandIf/include" --display_error_number --diag_warning=225 --abi=eabi --preproc_with_compile --preproc_dependency="statmgr.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


