#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.C66{1,0,7.3,4
#
app.x66: package/cfg/app.x66.mak

clean::
	-$(RM) package/cfg/app.x66.mak
