################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
Ethernet_config.obj: ../Ethernet_config.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/bin/cl6x" -mv6600 --abi=eabi -O2 -g --include_path="D:/WorkLocation/Code_736/Code_736/src/steDrv/platform/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stemgr/diagif/include" --include_path="D:/TInew/bios_6_37_02_27/packages" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/genutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/3rdparty/gsmL1/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/gsmutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/dataIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/status/include" --include_path="D:/TInew/xdctools_3_25_03_72/packages" --include_path="D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/include" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/platform/evmc6678l/platform_lib/include" --include_path="D:/TInew/ipc_3_21_00_07/packages" --gcc --define=_DEBUG --define=_TMS320C6400 --display_error_number --diag_warning=225 --opt_for_speed=3 --preproc_with_compile --preproc_dependency="Ethernet_config.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Gpi.obj: D:/WorkLocation/Code_736/Code_736/src/steDrv/platform/src/Gpi.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/bin/cl6x" -mv6600 --abi=eabi -O2 -g --include_path="D:/WorkLocation/Code_736/Code_736/src/steDrv/platform/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stemgr/diagif/include" --include_path="D:/TInew/bios_6_37_02_27/packages" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/genutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/3rdparty/gsmL1/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/gsmutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/dataIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/status/include" --include_path="D:/TInew/xdctools_3_25_03_72/packages" --include_path="D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/include" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/platform/evmc6678l/platform_lib/include" --include_path="D:/TInew/ipc_3_21_00_07/packages" --gcc --define=_DEBUG --define=_TMS320C6400 --display_error_number --diag_warning=225 --opt_for_speed=3 --preproc_with_compile --preproc_dependency="Gpi.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Gpio.obj: D:/WorkLocation/Code_736/Code_736/src/steDrv/platform/src/Gpio.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/bin/cl6x" -mv6600 --abi=eabi -O2 -g --include_path="D:/WorkLocation/Code_736/Code_736/src/steDrv/platform/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stemgr/diagif/include" --include_path="D:/TInew/bios_6_37_02_27/packages" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/genutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/3rdparty/gsmL1/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/gsmutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/dataIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/status/include" --include_path="D:/TInew/xdctools_3_25_03_72/packages" --include_path="D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/include" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/platform/evmc6678l/platform_lib/include" --include_path="D:/TInew/ipc_3_21_00_07/packages" --gcc --define=_DEBUG --define=_TMS320C6400 --display_error_number --diag_warning=225 --opt_for_speed=3 --preproc_with_compile --preproc_dependency="Gpio.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Gpo.obj: D:/WorkLocation/Code_736/Code_736/src/steDrv/platform/src/Gpo.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/bin/cl6x" -mv6600 --abi=eabi -O2 -g --include_path="D:/WorkLocation/Code_736/Code_736/src/steDrv/platform/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stemgr/diagif/include" --include_path="D:/TInew/bios_6_37_02_27/packages" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/genutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/3rdparty/gsmL1/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/gsmutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/dataIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/status/include" --include_path="D:/TInew/xdctools_3_25_03_72/packages" --include_path="D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/include" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/platform/evmc6678l/platform_lib/include" --include_path="D:/TInew/ipc_3_21_00_07/packages" --gcc --define=_DEBUG --define=_TMS320C6400 --display_error_number --diag_warning=225 --opt_for_speed=3 --preproc_with_compile --preproc_dependency="Gpo.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Mcbsp.obj: D:/WorkLocation/Code_736/Code_736/src/steDrv/platform/src/Mcbsp.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/bin/cl6x" -mv6600 --abi=eabi -O2 -g --include_path="D:/WorkLocation/Code_736/Code_736/src/steDrv/platform/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stemgr/diagif/include" --include_path="D:/TInew/bios_6_37_02_27/packages" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/genutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/3rdparty/gsmL1/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/gsmutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/dataIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/status/include" --include_path="D:/TInew/xdctools_3_25_03_72/packages" --include_path="D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/include" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/platform/evmc6678l/platform_lib/include" --include_path="D:/TInew/ipc_3_21_00_07/packages" --gcc --define=_DEBUG --define=_TMS320C6400 --display_error_number --diag_warning=225 --opt_for_speed=3 --preproc_with_compile --preproc_dependency="Mcbsp.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Srio.obj: D:/WorkLocation/Code_736/Code_736/src/steDrv/platform/src/Srio.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/bin/cl6x" -mv6600 --abi=eabi -O2 -g --include_path="D:/WorkLocation/Code_736/Code_736/src/steDrv/platform/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stemgr/diagif/include" --include_path="D:/TInew/bios_6_37_02_27/packages" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/genutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/3rdparty/gsmL1/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/gsmutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/dataIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/status/include" --include_path="D:/TInew/xdctools_3_25_03_72/packages" --include_path="D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/include" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/platform/evmc6678l/platform_lib/include" --include_path="D:/TInew/ipc_3_21_00_07/packages" --gcc --define=_DEBUG --define=_TMS320C6400 --display_error_number --diag_warning=225 --opt_for_speed=3 --preproc_with_compile --preproc_dependency="Srio.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Srio_devconfig.obj: ../Srio_devconfig.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/bin/cl6x" -mv6600 --abi=eabi -O2 -g --include_path="D:/WorkLocation/Code_736/Code_736/src/steDrv/platform/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stemgr/diagif/include" --include_path="D:/TInew/bios_6_37_02_27/packages" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/genutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/3rdparty/gsmL1/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/gsmutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/dataIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/status/include" --include_path="D:/TInew/xdctools_3_25_03_72/packages" --include_path="D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/include" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/platform/evmc6678l/platform_lib/include" --include_path="D:/TInew/ipc_3_21_00_07/packages" --gcc --define=_DEBUG --define=_TMS320C6400 --display_error_number --diag_warning=225 --opt_for_speed=3 --preproc_with_compile --preproc_dependency="Srio_devconfig.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

classify1_bin.obj: ../classify1_bin.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/bin/cl6x" -mv6600 --abi=eabi -O2 -g --include_path="D:/WorkLocation/Code_736/Code_736/src/steDrv/platform/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stemgr/diagif/include" --include_path="D:/TInew/bios_6_37_02_27/packages" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/genutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/3rdparty/gsmL1/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/gsmutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/dataIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/status/include" --include_path="D:/TInew/xdctools_3_25_03_72/packages" --include_path="D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/include" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/platform/evmc6678l/platform_lib/include" --include_path="D:/TInew/ipc_3_21_00_07/packages" --gcc --define=_DEBUG --define=_TMS320C6400 --display_error_number --diag_warning=225 --opt_for_speed=3 --preproc_with_compile --preproc_dependency="classify1_bin.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

classify2_bin.obj: ../classify2_bin.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/bin/cl6x" -mv6600 --abi=eabi -O2 -g --include_path="D:/WorkLocation/Code_736/Code_736/src/steDrv/platform/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stemgr/diagif/include" --include_path="D:/TInew/bios_6_37_02_27/packages" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/genutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/3rdparty/gsmL1/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/gsmutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/dataIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/status/include" --include_path="D:/TInew/xdctools_3_25_03_72/packages" --include_path="D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/include" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/platform/evmc6678l/platform_lib/include" --include_path="D:/TInew/ipc_3_21_00_07/packages" --gcc --define=_DEBUG --define=_TMS320C6400 --display_error_number --diag_warning=225 --opt_for_speed=3 --preproc_with_compile --preproc_dependency="classify2_bin.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cppi_device.obj: ../cppi_device.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/bin/cl6x" -mv6600 --abi=eabi -O2 -g --include_path="D:/WorkLocation/Code_736/Code_736/src/steDrv/platform/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stemgr/diagif/include" --include_path="D:/TInew/bios_6_37_02_27/packages" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/genutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/3rdparty/gsmL1/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/gsmutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/dataIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/status/include" --include_path="D:/TInew/xdctools_3_25_03_72/packages" --include_path="D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/include" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/platform/evmc6678l/platform_lib/include" --include_path="D:/TInew/ipc_3_21_00_07/packages" --gcc --define=_DEBUG --define=_TMS320C6400 --display_error_number --diag_warning=225 --opt_for_speed=3 --preproc_with_compile --preproc_dependency="cppi_device.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cppi_qmss_mgmt.obj: ../cppi_qmss_mgmt.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/bin/cl6x" -mv6600 --abi=eabi -O2 -g --include_path="D:/WorkLocation/Code_736/Code_736/src/steDrv/platform/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stemgr/diagif/include" --include_path="D:/TInew/bios_6_37_02_27/packages" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/genutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/3rdparty/gsmL1/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/gsmutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/dataIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/status/include" --include_path="D:/TInew/xdctools_3_25_03_72/packages" --include_path="D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/include" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/platform/evmc6678l/platform_lib/include" --include_path="D:/TInew/ipc_3_21_00_07/packages" --gcc --define=_DEBUG --define=_TMS320C6400 --display_error_number --diag_warning=225 --opt_for_speed=3 --preproc_with_compile --preproc_dependency="cppi_qmss_mgmt.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cpsw_mgmt.obj: ../cpsw_mgmt.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/bin/cl6x" -mv6600 --abi=eabi -O2 -g --include_path="D:/WorkLocation/Code_736/Code_736/src/steDrv/platform/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stemgr/diagif/include" --include_path="D:/TInew/bios_6_37_02_27/packages" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/genutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/3rdparty/gsmL1/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/gsmutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/dataIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/status/include" --include_path="D:/TInew/xdctools_3_25_03_72/packages" --include_path="D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/include" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/platform/evmc6678l/platform_lib/include" --include_path="D:/TInew/ipc_3_21_00_07/packages" --gcc --define=_DEBUG --define=_TMS320C6400 --display_error_number --diag_warning=225 --opt_for_speed=3 --preproc_with_compile --preproc_dependency="cpsw_mgmt.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

flash.obj: ../flash.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/bin/cl6x" -mv6600 --abi=eabi -O2 -g --include_path="D:/WorkLocation/Code_736/Code_736/src/steDrv/platform/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stemgr/diagif/include" --include_path="D:/TInew/bios_6_37_02_27/packages" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/genutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/3rdparty/gsmL1/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/gsmutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/dataIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/status/include" --include_path="D:/TInew/xdctools_3_25_03_72/packages" --include_path="D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/include" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/platform/evmc6678l/platform_lib/include" --include_path="D:/TInew/ipc_3_21_00_07/packages" --gcc --define=_DEBUG --define=_TMS320C6400 --display_error_number --diag_warning=225 --opt_for_speed=3 --preproc_with_compile --preproc_dependency="flash.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

pa_mgmt.obj: ../pa_mgmt.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/bin/cl6x" -mv6600 --abi=eabi -O2 -g --include_path="D:/WorkLocation/Code_736/Code_736/src/steDrv/platform/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stemgr/diagif/include" --include_path="D:/TInew/bios_6_37_02_27/packages" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/genutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/3rdparty/gsmL1/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/gsmutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/dataIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/status/include" --include_path="D:/TInew/xdctools_3_25_03_72/packages" --include_path="D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/include" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/platform/evmc6678l/platform_lib/include" --include_path="D:/TInew/ipc_3_21_00_07/packages" --gcc --define=_DEBUG --define=_TMS320C6400 --display_error_number --diag_warning=225 --opt_for_speed=3 --preproc_with_compile --preproc_dependency="pa_mgmt.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

pam_bin.obj: ../pam_bin.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/bin/cl6x" -mv6600 --abi=eabi -O2 -g --include_path="D:/WorkLocation/Code_736/Code_736/src/steDrv/platform/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stemgr/diagif/include" --include_path="D:/TInew/bios_6_37_02_27/packages" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/genutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/3rdparty/gsmL1/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/gsmutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/dataIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/status/include" --include_path="D:/TInew/xdctools_3_25_03_72/packages" --include_path="D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/include" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/platform/evmc6678l/platform_lib/include" --include_path="D:/TInew/ipc_3_21_00_07/packages" --gcc --define=_DEBUG --define=_TMS320C6400 --display_error_number --diag_warning=225 --opt_for_speed=3 --preproc_with_compile --preproc_dependency="pam_bin.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

phy.obj: ../phy.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/bin/cl6x" -mv6600 --abi=eabi -O2 -g --include_path="D:/WorkLocation/Code_736/Code_736/src/steDrv/platform/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stemgr/diagif/include" --include_path="D:/TInew/bios_6_37_02_27/packages" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/genutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/3rdparty/gsmL1/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/gsmutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/dataIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/status/include" --include_path="D:/TInew/xdctools_3_25_03_72/packages" --include_path="D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/include" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/platform/evmc6678l/platform_lib/include" --include_path="D:/TInew/ipc_3_21_00_07/packages" --gcc --define=_DEBUG --define=_TMS320C6400 --display_error_number --diag_warning=225 --opt_for_speed=3 --preproc_with_compile --preproc_dependency="phy.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

phy_read_write.obj: ../phy_read_write.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/bin/cl6x" -mv6600 --abi=eabi -O2 -g --include_path="D:/WorkLocation/Code_736/Code_736/src/steDrv/platform/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stemgr/diagif/include" --include_path="D:/TInew/bios_6_37_02_27/packages" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/genutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/3rdparty/gsmL1/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/gsmutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/dataIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/status/include" --include_path="D:/TInew/xdctools_3_25_03_72/packages" --include_path="D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/include" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/platform/evmc6678l/platform_lib/include" --include_path="D:/TInew/ipc_3_21_00_07/packages" --gcc --define=_DEBUG --define=_TMS320C6400 --display_error_number --diag_warning=225 --opt_for_speed=3 --preproc_with_compile --preproc_dependency="phy_read_write.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

qmss_device.obj: ../qmss_device.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/bin/cl6x" -mv6600 --abi=eabi -O2 -g --include_path="D:/WorkLocation/Code_736/Code_736/src/steDrv/platform/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stemgr/diagif/include" --include_path="D:/TInew/bios_6_37_02_27/packages" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/genutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/3rdparty/gsmL1/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/gsmutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/dataIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/status/include" --include_path="D:/TInew/xdctools_3_25_03_72/packages" --include_path="D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/include" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/platform/evmc6678l/platform_lib/include" --include_path="D:/TInew/ipc_3_21_00_07/packages" --gcc --define=_DEBUG --define=_TMS320C6400 --display_error_number --diag_warning=225 --opt_for_speed=3 --preproc_with_compile --preproc_dependency="qmss_device.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

singlecore_osal.obj: ../singlecore_osal.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/bin/cl6x" -mv6600 --abi=eabi -O2 -g --include_path="D:/WorkLocation/Code_736/Code_736/src/steDrv/platform/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stemgr/diagif/include" --include_path="D:/TInew/bios_6_37_02_27/packages" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/genutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/3rdparty/gsmL1/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/gsmutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/dataIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/status/include" --include_path="D:/TInew/xdctools_3_25_03_72/packages" --include_path="D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/include" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/platform/evmc6678l/platform_lib/include" --include_path="D:/TInew/ipc_3_21_00_07/packages" --gcc --define=_DEBUG --define=_TMS320C6400 --display_error_number --diag_warning=225 --opt_for_speed=3 --preproc_with_compile --preproc_dependency="singlecore_osal.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

spi.obj: ../spi.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/bin/cl6x" -mv6600 --abi=eabi -O2 -g --include_path="D:/WorkLocation/Code_736/Code_736/src/steDrv/platform/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stemgr/diagif/include" --include_path="D:/TInew/bios_6_37_02_27/packages" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/genutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/3rdparty/gsmL1/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/gsmutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/dataIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/status/include" --include_path="D:/TInew/xdctools_3_25_03_72/packages" --include_path="D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/include" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/platform/evmc6678l/platform_lib/include" --include_path="D:/TInew/ipc_3_21_00_07/packages" --gcc --define=_DEBUG --define=_TMS320C6400 --display_error_number --diag_warning=225 --opt_for_speed=3 --preproc_with_compile --preproc_dependency="spi.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

uart.obj: ../uart.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/bin/cl6x" -mv6600 --abi=eabi -O2 -g --include_path="D:/WorkLocation/Code_736/Code_736/src/steDrv/platform/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stemgr/diagif/include" --include_path="D:/TInew/bios_6_37_02_27/packages" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/genutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/3rdparty/gsmL1/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/gsmutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/dataIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/status/include" --include_path="D:/TInew/xdctools_3_25_03_72/packages" --include_path="D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/include" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/platform/evmc6678l/platform_lib/include" --include_path="D:/TInew/ipc_3_21_00_07/packages" --gcc --define=_DEBUG --define=_TMS320C6400 --display_error_number --diag_warning=225 --opt_for_speed=3 --preproc_with_compile --preproc_dependency="uart.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


