################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
A5_1Decipher.obj: D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/src/A5_1Decipher.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/bin/cl6x" -mv6600 --abi=eabi -O2 -g --include_path="D:/TInew/ipc_3_21_00_07/packages" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/3rdParty/gsmL1/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/gsmutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/genutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stemgr/dataif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/commandif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stemgr/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/diagif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/status/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stedrv/platform/include" --include_path="D:/TInew/bios_6_37_02_27/packages" --include_path="D:/TInew/xdctools_3_25_03_72/packages" --include_path="D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/include" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/platform/evmc6678l/platform_lib/include" --include_path="D:/TInew/uia_1_03_01_08/packages" --gcc --define=_DEBUG --define=_TMS320C6400 --display_error_number --diag_warning=225 --opt_for_speed=3 --preproc_with_compile --preproc_dependency="A5_1Decipher.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

GSMConfig.obj: D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/src/GSMConfig.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/bin/cl6x" -mv6600 --abi=eabi -O2 -g --include_path="D:/TInew/ipc_3_21_00_07/packages" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/3rdParty/gsmL1/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/gsmutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/genutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stemgr/dataif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/commandif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stemgr/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/diagif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/status/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stedrv/platform/include" --include_path="D:/TInew/bios_6_37_02_27/packages" --include_path="D:/TInew/xdctools_3_25_03_72/packages" --include_path="D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/include" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/platform/evmc6678l/platform_lib/include" --include_path="D:/TInew/uia_1_03_01_08/packages" --gcc --define=_DEBUG --define=_TMS320C6400 --display_error_number --diag_warning=225 --opt_for_speed=3 --preproc_with_compile --preproc_dependency="GSMConfig.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

L1Config.obj: D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/src/L1Config.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/bin/cl6x" -mv6600 --abi=eabi -O2 -g --include_path="D:/TInew/ipc_3_21_00_07/packages" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/3rdParty/gsmL1/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/gsmutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/genutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stemgr/dataif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/commandif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stemgr/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/diagif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/status/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stedrv/platform/include" --include_path="D:/TInew/bios_6_37_02_27/packages" --include_path="D:/TInew/xdctools_3_25_03_72/packages" --include_path="D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/include" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/platform/evmc6678l/platform_lib/include" --include_path="D:/TInew/uia_1_03_01_08/packages" --gcc --define=_DEBUG --define=_TMS320C6400 --display_error_number --diag_warning=225 --opt_for_speed=3 --preproc_with_compile --preproc_dependency="L1Config.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

L1Manager.obj: D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/src/L1Manager.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/bin/cl6x" -mv6600 --abi=eabi -O2 -g --include_path="D:/TInew/ipc_3_21_00_07/packages" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/3rdParty/gsmL1/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/gsmutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/genutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stemgr/dataif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/commandif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stemgr/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/diagif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/status/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stedrv/platform/include" --include_path="D:/TInew/bios_6_37_02_27/packages" --include_path="D:/TInew/xdctools_3_25_03_72/packages" --include_path="D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/include" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/platform/evmc6678l/platform_lib/include" --include_path="D:/TInew/uia_1_03_01_08/packages" --gcc --define=_DEBUG --define=_TMS320C6400 --display_error_number --diag_warning=225 --opt_for_speed=3 --preproc_with_compile --preproc_dependency="L1Manager.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

L1Receiver.obj: D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/src/L1Receiver.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/bin/cl6x" -mv6600 --abi=eabi -O2 -g --include_path="D:/TInew/ipc_3_21_00_07/packages" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/3rdParty/gsmL1/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/gsmutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/genutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stemgr/dataif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/commandif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stemgr/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/diagif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/status/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stedrv/platform/include" --include_path="D:/TInew/bios_6_37_02_27/packages" --include_path="D:/TInew/xdctools_3_25_03_72/packages" --include_path="D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/include" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/platform/evmc6678l/platform_lib/include" --include_path="D:/TInew/uia_1_03_01_08/packages" --gcc --define=_DEBUG --define=_TMS320C6400 --display_error_number --diag_warning=225 --opt_for_speed=3 --preproc_with_compile --preproc_dependency="L1Receiver.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

RxManager.obj: D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/src/RxManager.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/bin/cl6x" -mv6600 --abi=eabi -O2 -g --include_path="D:/TInew/ipc_3_21_00_07/packages" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/3rdParty/gsmL1/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/gsmutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/genutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stemgr/dataif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/commandif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stemgr/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/diagif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/status/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stedrv/platform/include" --include_path="D:/TInew/bios_6_37_02_27/packages" --include_path="D:/TInew/xdctools_3_25_03_72/packages" --include_path="D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/include" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/platform/evmc6678l/platform_lib/include" --include_path="D:/TInew/uia_1_03_01_08/packages" --gcc --define=_DEBUG --define=_TMS320C6400 --display_error_number --diag_warning=225 --opt_for_speed=3 --preproc_with_compile --preproc_dependency="RxManager.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

TRXCommon.obj: D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/src/TRXCommon.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/bin/cl6x" -mv6600 --abi=eabi -O2 -g --include_path="D:/TInew/ipc_3_21_00_07/packages" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/arfcn/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/3rdParty/gsmL1/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/gsmutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/commandIf/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steLib/genutil/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stemgr/dataif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/commandif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stemgr/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/diagif/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/steMgr/status/include" --include_path="D:/WorkLocation/Code_736/Code_736/src/stedrv/platform/include" --include_path="D:/TInew/bios_6_37_02_27/packages" --include_path="D:/TInew/xdctools_3_25_03_72/packages" --include_path="D:/TInew/ccsv5/tools/compiler/c6000_7.4.4/include" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="D:/TInew/pdk_C6678_1_1_2_6/packages/ti/platform/evmc6678l/platform_lib/include" --include_path="D:/TInew/uia_1_03_01_08/packages" --gcc --define=_DEBUG --define=_TMS320C6400 --display_error_number --diag_warning=225 --opt_for_speed=3 --preproc_with_compile --preproc_dependency="TRXCommon.pp" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


